ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_condition VARCHAR(50) DEFAULT 'NA_ENTREGA';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS due_date DATE;
ALTER TABLE financial_entries ALTER COLUMN due_date DROP NOT NULL;
